/**
 * DashTivi+ Collections — Curated content experiences
 *
 * Collections define WHAT to show and HOW to show it.
 * The homepage reads these to build a personalized, time-aware experience.
 *
 * Category IDs are from the Starshare/Xtream API.
 */

// ── Legacy Data (removed 2026-04-01) ────────────────────────────────
// RELOCATE_MAP, HIDDEN_STREAM_IDS, GEM_STREAM_IDS, BEST_OF_LIVE,
// AFRICAN_VIBES_IDS, CANAL_PLUS_IDS — all moved to Supabase database.
// Channels are now managed via tivi_channels (is_hidden, is_gem, experience).

// Legacy exports removed — all channel data now in Supabase

// ── Cherry-Picked Curated Experiences ──────────��────────────────────

/** "Best of Live" — the 15 channels that make DashTivi+ shine.
 *  Hand-picked mix: 3 sports, 3 news, 3 entertainment, 2 kids, 2 music, 2 documentary.
 *  These are the channels where someone tunes in and says "wow, this works." */

// ── Types ─────────────────────────────────────────────────────────

export interface Collection {
  id: string;
  name: string;
  emoji: string;
  description: string;
  type: 'live' | 'vod' | 'series';
  categoryIds: string[];
  /** Max items to show in a row */
  limit: number;
  /** Navigation target when tapping "See All" */
  navigateTo: string;
}

/** Smart collections are generated by the recommendation engine at runtime */
export interface SmartCollection {
  id: string;
  name: string;
  emoji: string;
  description: string;
  type: 'smart-vod' | 'smart-series';
  /** The underlying content type for rendering */
  contentType: 'vod' | 'series';
  navigateTo: string;
}

export interface CollectionCard {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  navigateTo: string;
}

export interface FeaturedHero {
  title: string;
  subtitle: string;
  cta: string;
  navigateTo: string;
  gradient: string;
}

// ── Homepage Row Collections ──────────────────────────────────────

export const HOMEPAGE_COLLECTIONS: Collection[] = [
  // 1. IDENTITY — what makes us different. African content nobody else has
  {
    id: 'live-sports',
    name: 'Live Sports',
    emoji: '',
    description: 'Live 4K · Premier League · Global Sports',
    type: 'live',
    categoryIds: [
      '345',  // DStv Super (32ch — SuperSport FHD, African sports backbone)
      '85',   // beIN Sports (124ch, 39 gems, 36 4K — strongest package)
      '353',  // Sky Sports UK (29ch, 26 gems)
      '578',  // Real 4K (31ch — UHD Sky Sports, LaLiga)
      '234',  // Football (28ch — SuperSport, Sky, TNT)
      '492',  // EPL (21ch — match day team channels)
    ],
    limit: 25,
    navigateTo: '/live/sports',
  },
  // 2. HOOK — fresh cinema, universal draw
  {
    id: 'fresh-movies',
    name: 'Just Dropped',
    emoji: '',
    description: 'Fresh 2025 & 2026 releases',
    type: 'vod',
    categoryIds: ['749', '597'], // English 2026, 2025
    limit: 25,
    navigateTo: '/movies',
  },
  // 3. MOTHERLAND — Canal+, DSTV, BBC, HBO. The global village
  {
    id: 'world-cinema',
    name: 'The Global Village',
    emoji: '',
    description: 'Africa · Europe · Americas — the whole world, one place',
    type: 'live',
    categoryIds: [
      '336',  // AFRICA CANAL+ (247ch — Africa Frenchn powerhouse)
      '343',  // DSTV Entertainment (84ch — African drama, Mzansi Magic)
      '2',    // USA (93ch — HBO, Starz, Showtime)
      '3',    // UK Entertainment (39ch — Ch4, Comedy Central, Sky)
      '414',  // UK General (26ch — BBC One FHD, ITV FHD)
      '86',   // MBC Arabic (46ch — MBC 1-5, Drama, Max)
    ],
    limit: 25,
    navigateTo: '/live/africa',
  },
  // 4. PREMIUM — 4K signals quality, builds confidence
  {
    id: 'cinema-4k',
    name: '4K Experience',
    emoji: '',
    description: 'Ultra HD blockbusters — crystal clear',
    type: 'vod',
    categoryIds: ['122', '34'],  // 4K, Blockbuster
    limit: 25,
    navigateTo: '/movies',
  },
  // 5. DEPTH — binge material keeps them coming back
  {
    id: 'k-drama-turkish',
    name: 'Binge-Worthy',
    emoji: '',
    description: 'K-Drama, Turkish & international series',
    type: 'series',
    categoryIds: ['267', '99'],  // Korean, Turkish
    limit: 25,
    navigateTo: '/series',
  },
  // 6. INFORM — trust anchor, shows we're serious
  {
    id: 'news-world',
    name: 'Stay Informed',
    emoji: '',
    description: 'World News · 4K · Breaking · 24/7',
    type: 'live',
    categoryIds: [
      '82',   // English News (22ch — CNN HD, BBC News, Sky News)
      '417',  // UK News (15ch — CNBC FHD, CNN FHD)
      '165',  // Arabic News (44ch — Al Jazeera 4K, France 24)
    ],
    limit: 20,
    navigateTo: '/live/news',
  },
  // 7. WARMTH — ends on family, softens the scroll
  {
    id: 'kids-family',
    name: 'Kids & Family',
    emoji: '',
    description: 'Disney 4K, Nickelodeon, Cartoon Network',
    type: 'live',
    categoryIds: [
      '410',  // UK Kids (12ch — Cartoon Network FHD, CBeebies, Nick)
      '32',   // Kids (46ch — Disney 4K, Nick, CN, CBeebies)
    ],
    limit: 25,
    navigateTo: '/live/kids',
  },
];

// ── Quick-tap Collection Cards (vibes navigation) ─────────────────

export const COLLECTION_CARDS: CollectionCard[] = [
  { id: 'sports', name: 'Sports', emoji: '', gradient: 'from-primary/30 to-primary-dark/30', navigateTo: '/live/sports' },
  { id: 'movies', name: 'Movies', emoji: '', gradient: 'from-primary/25 to-primary-dark/25', navigateTo: '/movies' },
  { id: 'news', name: 'News', emoji: '', gradient: 'from-primary/20 to-white/5', navigateTo: '/live/news' },
  { id: 'africa', name: 'The Motherland', emoji: '', gradient: 'from-accent/20 to-accent-gold/10', navigateTo: '/live/africa' },
  { id: 'series', name: 'Series', emoji: '', gradient: 'from-primary/30 to-primary-dark/20', navigateTo: '/series' },
  { id: 'kids', name: 'Kids', emoji: '', gradient: 'from-primary-light/20 to-primary/15', navigateTo: '/live/kids' },
  { id: 'music', name: 'Music', emoji: '', gradient: 'from-primary/25 to-primary-light/15', navigateTo: '/live/music' },
  { id: 'faith', name: 'Faith', emoji: '', gradient: 'from-accent-gold/15 to-primary/10', navigateTo: '/live/faith' },
];

// ── Time-aware Featured Hero ──────────────────────────────────────

export function getFeaturedHero(): FeaturedHero {
  const hour = new Date().getHours();

  // Morning (6am-12pm)
  if (hour >= 6 && hour < 12) {
    return {
      title: 'Good Morning',
      subtitle: 'Start your day informed. World-class news and morning entertainment.',
      cta: 'Start Watching',
      navigateTo: '/live',
      gradient: 'from-blue-600/20 via-[#0A0A0A] to-sky-900/10',
    };
  }

  // Afternoon (12pm-6pm)
  if (hour >= 12 && hour < 18) {
    return {
      title: 'Afternoon Escape',
      subtitle: 'Award-winning movies and handpicked series. Your next favorite is here.',
      cta: 'Explore',
      navigateTo: '/movies',
      gradient: 'from-amber-600/15 via-[#0A0A0A] to-orange-900/10',
    };
  }

  // Evening (6pm-11pm)
  if (hour >= 18 && hour < 23) {
    return {
      title: 'Prime Time',
      subtitle: 'Live sports, fresh cinema, and curated series. Your evening, elevated.',
      cta: 'Watch Now',
      navigateTo: '/live',
      gradient: 'from-primary/20 via-[#0A0A0A] to-primary-dark/10',
    };
  }

  // Late night (11pm-6am)
  return {
    title: 'Late Night',
    subtitle: 'The best series for those who stay up. Something new awaits.',
    cta: 'Dive In',
    navigateTo: '/series',
    gradient: 'from-indigo-600/15 via-[#0A0A0A] to-violet-900/10',
  };
}

// ── Movie Featured Categories (reordered for audience) ────────────

export const MOVIE_FEATURED_CATS = [
  { id: '749', name: 'New 2026' },        // 239 movies
  { id: '597', name: '2025 Hits' },       // 2,127 movies
  { id: '525', name: '2024' },            // 2,617 movies
  { id: '122', name: '4K' },              // 1,058 movies
  { id: '34', name: 'Blockbuster' },      // 1,002 movies
  { id: '240', name: 'Award Winners' },   // 142 movies
  { id: '95', name: 'Turkish' },          // 854 movies
  { id: '33', name: 'Bollywood' },        // 2,683 movies
  { id: '69', name: 'Kids' },             // 441 movies
  { id: '96', name: 'Arabic Sub' },       // 684 movies
  { id: '148', name: 'Horror' },          // 188 movies
];

// ── Series Featured Categories ────────────────────────────────────

export const SERIES_FEATURED_CATS = [
  { id: '106', name: 'Netflix' },         // 2,543 series
  { id: '108', name: 'Prime Video' },     // 1,580 series
  { id: '102', name: 'Disney+' },         // 818 series
  { id: '188', name: 'HBO' },             // 381 series
  { id: '114', name: 'Apple TV+' },       // 346 series
  { id: '209', name: 'Hulu' },            // 334 series
  { id: '202', name: 'BBC' },             // 315 series
  { id: '249', name: 'Paramount+' },      // 154 series
  { id: '99', name: 'Turkish' },          // 1,142 series
  { id: '267', name: 'Korean' },          // 235 series
];

// ── Live TV Themed Collections ───────────────────────────────────

export interface LiveTheme {
  id: string;
  name: string;
  emoji: string;
  description?: string;
  categoryIds: string[];
  gradient: string;
  glowColor: string;
}

export const LIVETV_THEMES: LiveTheme[] = [
  {
    id: 'sports',
    name: 'Sports',
    emoji: '',
    description: '4K · Live · Every League · Every Match',
    categoryIds: [
      '85',   // beIN Sports (124ch, 39 gems, 36 4K — strongest sports package)
      '578',  // Real 4K (31ch — true UHD Sky Sports, LaLiga TV)
      '353',  // Sky Sports UK (29ch, 26 gems — FHD/HD, all disciplines)
      '483',  // Sky Sports (additional feeds)
      '234',  // Football (28ch, 19 gems — SuperSport, Sky, TNT, club channels)
      '345',  // DStv Super (32ch — SuperSport FHD, African sports backbone)
      '427',  // DStv Super (additional — SuperSport HD)
      '492',  // EPL (21ch — match day team channels)
      '5',    // Cricket (57ch, 37 gems)
      '6',    // Sports General
      '342',  // Tennis/Racing
      '550',  // Rugby (20ch, 19 gems — Sky Sport NZ FHD)
      '138',  // Boxing
      '212',  // Fighting
      '356',  // India Sports
      '156',  // Arabic Sports
      '137',  // Fox Australia Sports (8 alive)
      '516',  // NFL (match day)
      '139',  // UK Sports Mix (10ch)
      '726',  // MLS (49 alive)
      '328',  // MLB (32 alive)
      '190',  // PPV Live Events (72ch)
      '807',  // IPL 2026 (9ch)
      '808',  // PSL 2026 (2ch)
      '542',  // Optus Sports (11 alive)
      '543',  // Spark Sports (8 alive)
    ],
    gradient: 'from-primary to-primary-dark',
    glowColor: 'shadow-primary/20',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    emoji: '',
    description: 'Drama · Comedy · Reality · Worldwide',
    categoryIds: [
      '3',    // UK Entertainment (39ch, 8 gems — Ch4, Ch5, Comedy Central, Sky)
      '414',  // UK General (26ch, 16 gems — BBC One FHD, ITV FHD)
      '2',    // USA (93ch, 42 gems — HBO, Starz, Showtime)
      '11',   // France (162ch, 86% alive — Canal+, TF1, M6, France 2/3/5)
      '39',   // Poland (192ch — Canal+ Premium/Film/Sport/Seriale FHD)
      '247',  // India Entertainment
      '338',  // India Entertainment (additional)
      '19',   // UK Asian (38ch, 9 gems)
      '24',   // US 24/7
      '343',  // DSTV Entertainment (African Drama subtab)
      '336',  // Africa Canal+ (African Drama subtab)
      '344',  // DSTV Movies (Nollywood subtab)
      '429',  // DSTV Movies Alt (Nollywood subtab)
    ],
    gradient: 'from-primary/80 to-primary-dark/80',
    glowColor: 'shadow-primary/20',
  },
  {
    id: 'news',
    name: 'News',
    emoji: '',
    description: 'Breaking · World · Arabic · 24/7',
    categoryIds: [
      '82',   // English News (22ch, 14 gems — CNN HD, BBC News, Sky News, Fox)
      '417',  // UK News (15ch, 11 gems — CNBC FHD, CNN FHD, Sky News HD)
      '165',  // Arabic News (44ch, 12 gems — Al Jazeera 4K/HD, France 24 Arabic)
      '730',  // Indian News (Malayalam)
      '77',   // Indian News (47ch, 5 gems — NDTV, CNN News 18)
      '98',   // Pakistan News (47ch)
    ],
    gradient: 'from-primary-dark to-primary/70',
    glowColor: 'shadow-primary-dark/20',
  },
  {
    id: 'kids',
    name: 'Kids & Family',
    emoji: '',
    description: 'Disney, Nick, Cartoon Network',
    categoryIds: [
      '410',  // UK Kids (12ch, 11 gems — CN FHD, CBeebies FHD, Nick FHD, Sky Kids FHD)
      '32',   // Kids (46ch, 29 gems — Disney 4K, Nick 4K, CN HD, CBeebies)
      '347',  // DSTV Kids (13ch)
      '430',  // DSTV Kids FHD (15ch)
    ],
    gradient: 'from-primary-light to-primary',
    glowColor: 'shadow-primary-light/20',
  },
  {
    id: 'movies247',
    name: 'Movie Channels',
    emoji: '',
    description: '24/7 Cinema · Blockbusters · Bollywood',
    categoryIds: [
      '87',   // beIN Movies (29ch, 8 gems — 4K + HD, Cinema + Series + Drama)
      '275',  // English Movies 24/7
      '57',   // Netflix Movies 24/7
      '340',  // India English Movies (29ch, 11 gems — Star Movies 4K, Colors Infinity 4K)
      '339',  // India Hindi Movies (23ch, 10 gems — Sony Max 4K, Star Gold 4K)
      '282',  // Bollywood Movies 24/7
      '280',  // Amazon Movies 24/7
      '413',  // UK Movies (41 alive — Sky Cinema)
      '344',  // DSTV Movies (7ch)
      '429',  // DSTV Movies FHD (9ch)
    ],
    gradient: 'from-primary-dark/90 to-accent/30',
    glowColor: 'shadow-primary-dark/20',
  },
  {
    id: 'faith',
    name: 'Faith',
    emoji: '',
    description: 'Islamic & Christian channels',
    categoryIds: [
      '123',  // Islamic (62ch)
      '561',  // Christian (16ch)
    ],
    gradient: 'from-accent-gold/40 to-primary/30',
    glowColor: 'shadow-accent-gold/20',
  },
  {
    id: 'music',
    name: 'Music & Vibes',
    emoji: '',
    description: 'MTV, Bollywood Beats, Arabic Vibes',
    categoryIds: [
      '416',  // UK Music
      '341',  // India Music (11ch, 4 gems)
      '555',  // Arabic Music
      '270',  // Bollywood Singers 24/7
      '287',  // Punjabi Singers 24/7
    ],
    gradient: 'from-primary to-primary-light/70',
    glowColor: 'shadow-primary/20',
  },
  {
    id: 'premium4k',
    name: 'Premium 4K',
    emoji: '',
    description: 'Ultra HD sports, movies & docs',
    categoryIds: [
      '578',  // Real 4K (31ch — Sky Sports UHD, LaLiga TV UHD, Sport TV UHD)
      '85',   // beIN Sports (36 4K channels — beIN 4K 1-9, Alkass 4K, Xtra 4K)
      '87',   // beIN Movies (14 4K channels — beIN Movies 4K 1-4, Series 4K)
      '337',  // India Documentary (7 4K — Discovery, NatGeo, Animal Planet)
      '340',  // India English Movies (11 4K — Star Movies, Colors Infinity)
      '339',  // India Hindi Movies (8 4K — Sony Max, Star Gold, Colors Cineplex)
      '356',  // India Sports (9 4K — Star Sports, Sony Ten)
    ],
    gradient: 'from-accent-gold/30 to-primary-dark/40',
    glowColor: 'shadow-accent-gold/20',
  },
  {
    id: 'documentary',
    name: 'Docs & Discovery',
    emoji: '',
    description: 'Discovery, NatGeo, Sky History',
    categoryIds: [
      '415',  // UK Documentary (19ch, 18 gems — Discovery FHD, Sky History, NatGeo, Sky Nature)
      '337',  // India Documentary (23ch, 17 gems — Discovery 4K, NatGeo 4K, Animal Planet 4K)
    ],
    gradient: 'from-primary-dark/80 to-primary/60',
    glowColor: 'shadow-primary-dark/20',
  },
];

// ── Sports Sub-types (for sub-tabs within Sports theme) ─────────

export interface SportType {
  id: string;
  name: string;
  categoryIds: string[];
  /** Optional name-based filter — channels must match at least one keyword (case-insensitive) */
  nameFilter?: string[];
  /** Optional name-based exclusion — channels matching any keyword are excluded */
  nameExclude?: string[];
}

// Child experiences within Sports — DASH-branded rooms
export const SPORT_TYPES: SportType[] = [
  { id: 'all', name: 'All Sports', categoryIds: ['85', '578', '353', '483', '234', '345', '427', '492', '5', '6', '342', '550', '138', '212', '356', '156', '137', '516', '139', '726', '328'] },
  { id: 'football', name: 'Football Non-Stop', categoryIds: ['492', '85', '234', '345'] },  // EPL team channels, beIN, general football, DStv SuperSport
  { id: 'bein', name: 'Premium 4K', categoryIds: ['85'] },   // 93% alive, all premium — 4K/FHD/HD
  { id: 'sky', name: 'UK Sports', categoryIds: ['578', '353', '483'] },  // 4K first, then FHD, then additional
  { id: 'cricket', name: 'Cricket Ground', categoryIds: ['5'] },  // 57ch, 37 gems
  { id: 'nfl', name: 'NFL', categoryIds: ['516'] },  // match day only — 5% alive outside game days
  { id: 'fans', name: 'Fans Space', categoryIds: ['234'] },  // LFC TV, MUTV, team channels
  { id: 'africa', name: 'African Football', categoryIds: ['234', '345', '427'] },  // SuperSport + DStv Super — African sports backbone
  { id: 'racing', name: 'Speed', categoryIds: ['342'] },
  { id: 'rugby', name: 'Rugby', categoryIds: ['550'] },  // 20ch, 19 gems — Sky Sport NZ
  { id: 'more', name: 'More', categoryIds: ['138', '212', '726', '328', '6'] },
];

// ── Child Experiences — sub-tabs within each mother theme ─────────
// Same SportType interface reused for all child experiences

export const ENTERTAINMENT_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['3', '414', '2', '11', '39', '247', '338', '19', '24'] },
  { id: 'uk', name: 'UK Lounge', categoryIds: ['414', '3'] },       // BBC, ITV, Ch4, Sky
  { id: 'usa', name: 'USA Tonight', categoryIds: ['2'] },           // HBO, Starz, Showtime
  { id: 'french', name: 'French & Europe', categoryIds: ['11', '39'] },  // France + Poland feeds, TF1, M6, Arte
  { id: 'african', name: 'African Drama', categoryIds: ['343', '336'] }, // African Entertainment
  { id: 'nollywood', name: 'Nollywood & Africa', categoryIds: ['344', '429', '343'] }, // African Movies + Entertainment
  { id: 'asian', name: 'Asian Vibes', categoryIds: ['247', '338', '19'] },
];

export const KIDS_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['410', '32'] },
  { id: 'cartoons', name: 'Cartoons', categoryIds: ['32', '410'], nameFilter: ['cartoon', 'nick', 'disney', 'boomerang', 'ben 10', 'ducktales', 'looney', 'sponge', 'avatar', 'spider', 'doraemon', 'shinchan', 'pj mask', 'peppa', 'paw'] },
  { id: 'littleones', name: 'Little Ones', categoryIds: ['32', '410'], nameFilter: ['baby', 'rhyme', 'panda', 'chu chu', 'finger', 'nursery', 'abcd', 'colour', 'boom buddies', 'hickory', 'shape', 'story', 'art-fun', 'cbeebies', 'nick jr', 'baraem', 'jeem'] },
  { id: 'shows', name: 'Shows', categoryIds: ['32', '410'], nameFilter: ['disney channel', 'disney xd', 'disney jr', 'nickelodeon', 'nick jr', 'sky kids', 'cartoon network', 'cbeebies', 'gulli', 'spacetoon', 'majid', 'discovery kids', 'baby tv', 'telekids', 'rotana kids'] },
  { id: 'ukkids', name: 'UK Kids', categoryIds: ['410'] },
];

export const CINEMA_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['87', '413', '429', '344', '340', '339', '275', '57', '282', '280'] },
  { id: 'sky', name: 'Sky Cinema', categoryIds: ['413'] },
  { id: 'bein', name: 'beIN Movies', categoryIds: ['87'] },
  { id: 'hbo', name: 'HBO & Premium', categoryIds: ['275', '413', '340'], nameFilter: ['hbo', 'showtime', 'starz', 'cinemax', 'lifetime movie'] },
  { id: 'action', name: 'Action', categoryIds: ['275', '340'], nameFilter: ['action', 'thriller', 'fast and furious', 'mission impossible', 'die hard', 'bourne', 'terminator', 'marine', 'war movie'] },
  { id: 'scifi', name: 'Sci-Fi & Fantasy', categoryIds: ['275', '340'], nameFilter: ['sci-fi', 'fantasy', 'star war', 'star trek', 'matrix', 'marvel', 'superman', 'spider man', 'lord of the ring', 'men in black', 'planet of the ape', 'alien', 'monsterverse', 'lego'] },
  { id: 'horror', name: 'Horror', categoryIds: ['275', '340'], nameFilter: ['horror', 'conjuring', 'saw', 'scary', 'friday the 13', 'resident evil', 'final destination', 'mummy'] },
  { id: 'family', name: 'Family', categoryIds: ['275', '413', '87'], nameFilter: ['family', 'kids', 'animated', 'toy story', 'ice age', 'shrek', 'kung fu panda', 'finding nemo', 'incredibles', 'despicable', 'chipmunks', 'muppet', 'how to train', 'jumanji'] },
  { id: 'nollywood', name: 'Nollywood', categoryIds: ['344', '429'] },
  { id: 'bollywood', name: 'Bollywood', categoryIds: ['282', '339', '340'] },
  { id: 'netflix', name: 'Netflix Loop', categoryIds: ['57'] },
];

export const MUSIC_TYPES: SportType[] = [
  { id: 'all', name: 'All Vibes', categoryIds: ['416', '341', '555', '270', '287'] },
  { id: 'afro', name: 'Afro Beats', categoryIds: ['555', '416'] },   // Trace Muzika (555) + MTV (416, includes MTV Base)
  { id: 'gospel', name: 'Gospel & Praise', categoryIds: ['561'] },  // Faith music crossover — essential for SL
  { id: 'mtv', name: 'MTV World', categoryIds: ['416'] },
  { id: 'bollywood', name: 'Bollywood Beats', categoryIds: ['341', '270'] },
  { id: 'throwback', name: 'Throwback', categoryIds: ['416'] },     // NOW 70s, 80s, 90s
  { id: 'arabic', name: 'Arabic Vibes', categoryIds: ['555'] },
  { id: 'latin', name: 'Latin Beats', categoryIds: ['287'] },
];

export const DISCOVERY_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['415', '337'] },
  { id: 'nature', name: 'Nature & Wild', categoryIds: ['337', '415'], nameFilter: ['nat geo', 'national geo', 'animal', 'bbc earth', 'planet earth', 'love nature', 'sky nature', 'myzen nature', 'zoo'] },
  { id: 'discovery', name: 'Discovery', categoryIds: ['337', '415'], nameFilter: ['discovery', 'science', 'turbo', 'curiosity'] },
  { id: 'history', name: 'History', categoryIds: ['415', '337'], nameFilter: ['history', 'museum', 'toute l\'histoire', 'histoire'] },
  { id: 'crime', name: 'True Crime', categoryIds: ['415', '337'], nameFilter: ['investigation', 'crime', 'court'] },
  { id: 'travel', name: 'Travel', categoryIds: ['415', '337'], nameFilter: ['travel', 'trek', 'equidia'] },
];

export const FAITH_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['123', '561'] },
  { id: 'islamic', name: 'Islamic', categoryIds: ['123'], nameExclude: ['quran', 'makkah', 'mecca', 'karbala', 'imam hussein'] },
  { id: 'quran', name: 'Quran', categoryIds: ['123'], nameFilter: ['quran', 'makkah', 'mecca', 'sudais', 'fateh', 'iqraa'] },
  { id: 'christian', name: 'Christian', categoryIds: ['561'] },
  { id: 'shia', name: 'Shia', categoryIds: ['123'], nameFilter: ['karbala', 'imam hussein', 'ahlulbayt', 'alzahra', 'thaqalayn', 'al manar'] },
];

// ── The Motherland — DSTV + Canal+ Africa Experience ─────────────
export const MOTHERLAND_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['336', '428', '343', '427', '345', '85', '11', '430', '347', '429', '344', '431', '346', '165', '82', '417', '32', '337', '275', '234'] },
  { id: 'supersport', name: 'Sports', categoryIds: ['427', '345', '234', '85'] },           // African sports + premium
  { id: 'canalplus', name: 'Africa French', categoryIds: ['336', '11'] },                  // Francophone African + France feeds
  { id: 'entertainment', name: 'Entertainment', categoryIds: ['428', '343'] },              // Africa Magic, BET, M-Net, kykNET
  { id: 'kids', name: 'Kids', categoryIds: ['430', '347', '32'] },                         // DSTV Kids FHD/HD + Cartoon Network, Disney
  { id: 'news', name: 'News', categoryIds: ['431', '346', '165', '82', '417'] },           // DSTV News, Al Jazeera, BBC, CNN, Arise
  { id: 'movies', name: 'Movies', categoryIds: ['429', '344', '275'] },                    // DSTV Movies + English genre
  { id: 'music', name: 'Music & Vibes', categoryIds: ['336', '11'] },                      // African music, gospel, urban
  { id: 'documentary', name: 'Documentary', categoryIds: ['337', '428'] },                 // NatGeo, Discovery via DSTV
];

// ── Europe Experience ─────────────────────────────────────────────
export const EUROPE_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['11', '15', '14', '39', '21', '29', '20', '44', '63', '579', '582', '774', '10', '132', '353', '483', '578', '413', '414', '415', '416', '410', '417', '3'] },
  { id: 'france', name: 'France', categoryIds: ['11'] },
  { id: 'germany', name: 'Germany', categoryIds: ['15'] },
  { id: 'uk', name: 'UK', categoryIds: ['3', '414', '413', '415', '416', '410', '417', '353', '483', '578'] },
  { id: 'italy', name: 'Italy', categoryIds: ['14'] },
  { id: 'poland', name: 'Poland', categoryIds: ['39'] },
  { id: 'netherlands', name: 'Netherlands', categoryIds: ['21'] },
  { id: 'balkans', name: 'Balkans', categoryIds: ['29', '20', '44'] },
  { id: 'scandinavia', name: 'Nordic', categoryIds: ['63', '579', '582'] },
  { id: 'greece', name: 'Greece', categoryIds: ['10'] },
];

// ── South Asian Experience ────────────────────────────────────────
export const SOUTH_ASIAN_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['247', '338', '18', '5', '356', '77', '731', '337', '341', '270', '287', '339', '340', '9', '292', '732', '733', '72', '73', '290', '728', '729', '727', '730', '81', '291', '75', '76', '7', '285', '282'] },
  { id: 'entertainment', name: 'Entertainment', categoryIds: ['247', '338'] },
  { id: 'cricket', name: 'Cricket', categoryIds: ['5'] },
  { id: 'movies', name: 'Movies', categoryIds: ['339', '340', '282'] },
  { id: 'news', name: 'News', categoryIds: ['77', '731'] },
  { id: 'music', name: 'Music', categoryIds: ['341', '270', '287'] },
  { id: 'tamil', name: 'Tamil', categoryIds: ['732', '733', '72'] },
  { id: 'bangla', name: 'Bangla', categoryIds: ['9', '292'] },
  { id: 'telugu', name: 'Telugu', categoryIds: ['73', '290'] },
];

// ── Americas Experience ───────────────────────────────────────────
export const AMERICAS_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['2', '31', '741', '24'] },
  { id: 'usa', name: 'USA', categoryIds: ['2'], nameFilter: ['us:', 'usa:', 'us ', 'usa '] },
  { id: 'canada', name: 'Canada', categoryIds: ['2', '741'], nameFilter: ['ca ', 'ca:', '|ca|', 'ca-fr', 'ca(fr)', 'tsn'] },
  { id: 'brazil', name: 'Brazil', categoryIds: ['31'] },
  { id: 'sports', name: 'Sports', categoryIds: ['2', '31'], nameFilter: ['espn', 'fox sport', 'nfl', 'nhl', 'mlb', 'nba', 'sportv', 'combate', 'tsn', 'sportsnet'] },
  { id: '247', name: '24/7', categoryIds: ['24'] },
];

// ── Arabic Experience ─────────────────────────────────────────────
export const ARABIC_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['86', '165', '156', '87', '13', '555', '181', '180', '178', '83', '549', '556', '554', '553', '548', '129'] },
  { id: 'mbc', name: 'MBC', categoryIds: ['86'] },
  { id: 'news', name: 'News', categoryIds: ['165'] },
  { id: 'sports', name: 'Sports', categoryIds: ['156'] },
  { id: 'movies', name: 'beIN Movies', categoryIds: ['87'] },
  { id: 'music', name: 'Music', categoryIds: ['555'] },
  { id: 'gulf', name: 'Gulf', categoryIds: ['181', '180', '178', '83', '549', '556', '554', '553', '548', '129'] },
];

// ── French Experience ─────────────────────────────────────────────
export const FRENCH_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['11', '336', '39'] },
  { id: 'france', name: 'France', categoryIds: ['11'], nameFilter: ['fra |', 'tf1', 'france 2', 'france 4', 'm6', 'bfm', 'rtl'] },
  { id: 'cinema', name: 'Cinema', categoryIds: ['11'], nameFilter: ['cin', 'ocs', 'action', 'serie club', 'syfy', 'warner', 'comedie', '13eme', 'crime district', 'drive in', 'novelas', 'scream'] },
  { id: 'sports', name: 'Sports', categoryIds: ['11'], nameFilter: ['bein', 'eurosport', 'sport', 'fight', 'fuel', 'auto'] },
  { id: 'kids', name: 'Kids', categoryIds: ['11'], nameFilter: ['cartoon', 'nickelodeon', 'gulli', 'boomerang', 'cartoonito', 'tele toon', 'canal j', 'dreamworks'] },
  { id: 'news', name: 'News', categoryIds: ['11'], nameFilter: ['bfm', 'euronews', 'france 24', 'b smart', 'tech & co'] },
  { id: 'canalplus', name: 'Africa French', categoryIds: ['336'] },
];

export const NEWS_TYPES: SportType[] = [
  { id: 'all', name: 'All News', categoryIds: ['82', '417', '165', '730', '77', '98'] },
  { id: 'world', name: 'World', categoryIds: ['82', '417'], nameFilter: ['cnn', 'bbc', 'sky news', 'nbc news', 'gb news', 'france 24 english', 'trt world'] },
  { id: 'business', name: 'Business', categoryIds: ['82', '417'], nameFilter: ['cnbc', 'bloomberg', 'business'] },
  { id: 'arabic', name: 'Arabic', categoryIds: ['165'] },
  { id: 'african', name: 'Africa', categoryIds: ['82', '417'], nameFilter: ['arise', 'tvc news', 'channels', 'ait'] },
  { id: 'asian', name: 'South Asia', categoryIds: ['77', '730', '98'] },
  { id: 'sports', name: 'Sports News', categoryIds: ['82', '417'], nameFilter: ['sky sports news', 'sport news', 'espn', 'esp news', 'fox sports news'] },
];

// ── WorldEX Region Genre Filters ─────────────────────────────────
// Genre pills within each WorldEX region — maps to Xtream category IDs
// "All" uses the region's default, genre pills load additional categories

export interface RegionGenre {
  id: string;
  name: string;
  categoryIds: string[];
}

export const REGION_GENRES: Record<string, RegionGenre[]> = {
  motherland: [
    { id: 'all', name: 'All', categoryIds: ['336', '428', '343', '427', '345', '85', '11'] },  // Canal+ Africa + DStv Ent + DStv Sports + beIN + France (incl. Trace Africa/Urban/Gospel)
    { id: 'sports', name: 'Sports', categoryIds: ['427', '345', '85', '234'] },  // DStv Super FHD + DStv Super + beIN (Arabic football massive in West Africa) + Football (SuperSport PL/LaLiga)
    { id: 'entertainment', name: 'Entertainment', categoryIds: ['428', '343', '336'] },  // DStv Ent FHD + DStv Ent + Canal+ Africa
    { id: 'music', name: 'Music', categoryIds: ['336', '11'] },        // Canal+ Africa music + France feed (Trace Africa HD, Trace Urban HD, Trace Gospel HD, NRJ Hits, M6 Music)
    { id: 'french', name: 'French', categoryIds: ['11', '336'] },      // France (Canal+, TF1, M6, Trace) + Canal+ Africa francophone
    { id: 'news', name: 'News', categoryIds: ['431', '346', '165'] },  // DStv News FHD + DStv News + Arabic News (Al Jazeera)
    { id: 'kids', name: 'Kids', categoryIds: ['430', '347'] },         // DStv Kids FHD + DStv Kids
    { id: 'movies', name: 'Movies', categoryIds: ['429', '344', '87'] }, // DStv Movies FHD + DStv Movies + beIN Movies
  ],
  sahara: [
    { id: 'all', name: 'All', categoryIds: ['86', '165', '156', '87', '13'] },
    { id: 'mbc', name: 'MBC', categoryIds: ['86'] },
    { id: 'news', name: 'News', categoryIds: ['165'] },
    { id: 'sports', name: 'Sports', categoryIds: ['156'] },
    { id: 'movies', name: 'beIN Movies', categoryIds: ['87'] },
    { id: 'music', name: 'Music', categoryIds: ['555'] },
    { id: 'gulf', name: 'Gulf States', categoryIds: ['181', '180', '178', '83', '549', '556', '554', '553', '548', '129'] },
  ],
  europe: [
    { id: 'all', name: 'All', categoryIds: ['11', '15', '14', '39'] },
    { id: 'france', name: 'France', categoryIds: ['11'] },
    { id: 'germany', name: 'Germany', categoryIds: ['15'] },
    { id: 'poland', name: 'Poland', categoryIds: ['39'] },
    { id: 'italy', name: 'Italy', categoryIds: ['14'] },
    { id: 'netherlands', name: 'Netherlands', categoryIds: ['21'] },
    { id: 'balkans', name: 'Balkans', categoryIds: ['29', '20', '44'] },
    { id: 'scandinavia', name: 'Scandinavia', categoryIds: ['63', '579', '582'] },
    { id: 'czech', name: 'Czech', categoryIds: ['774'] },
    { id: 'greece', name: 'Greece', categoryIds: ['10'] },
    { id: 'israel', name: 'Israel', categoryIds: ['132'] },
  ],
  persian: [
    { id: 'all', name: 'All', categoryIds: ['751', '28'] },
    { id: 'iran', name: 'Iran', categoryIds: ['751'] },
    { id: 'afghanistan', name: 'Afghanistan', categoryIds: ['28'] },
  ],
  southasia: [
    { id: 'all', name: 'All', categoryIds: ['247', '338', '18'] },
    { id: 'entertainment', name: 'Entertainment', categoryIds: ['247', '338'] },
    { id: 'cricket', name: 'Cricket', categoryIds: ['5'] },
    { id: 'sports', name: 'Sports', categoryIds: ['356'] },
    { id: 'news', name: 'News', categoryIds: ['77', '731'] },
    { id: 'docs', name: 'Discovery', categoryIds: ['337'] },
    { id: 'music', name: 'Music', categoryIds: ['341', '270', '287'] },
    { id: 'movies', name: 'Movies', categoryIds: ['339', '340'] },
    { id: 'bangla', name: 'Bangla', categoryIds: ['9', '292'] },
    { id: 'tamil', name: 'Tamil', categoryIds: ['732', '733', '72'] },
    { id: 'telugu', name: 'Telugu', categoryIds: ['73', '290'] },
    { id: 'malayalam', name: 'Malayalam', categoryIds: ['728', '729', '727', '730'] },
    { id: 'kannada', name: 'Kannada', categoryIds: ['81', '291'] },
    { id: 'punjabi', name: 'Punjabi', categoryIds: ['7', '285'] },
    { id: 'marathi', name: 'Marathi', categoryIds: ['75'] },
    { id: 'gujarati', name: 'Gujarati', categoryIds: ['76'] },
  ],
  crescent: [
    { id: 'all', name: 'All', categoryIds: ['4', '98', '42', '64'] },
    { id: 'pakistan', name: 'Pakistan', categoryIds: ['4'] },
    { id: 'news', name: 'News', categoryIds: ['98'] },
    { id: 'srilanka', name: 'Sri Lanka', categoryIds: ['42'] },
    { id: 'nepal', name: 'Nepal', categoryIds: ['64'] },
  ],
  isles: [
    { id: 'all', name: 'All', categoryIds: ['3', '414'] },
    { id: 'sports', name: 'Sports', categoryIds: ['483', '353'] },
    { id: 'entertainment', name: 'Entertainment', categoryIds: ['3'] },
    { id: 'news', name: 'News', categoryIds: ['417'] },
    { id: 'movies', name: 'Movies', categoryIds: ['413'] },
    { id: 'kids', name: 'Kids', categoryIds: ['410'] },
    { id: 'docs', name: 'Docs', categoryIds: ['415'] },
    { id: 'music', name: 'Music', categoryIds: ['416'] },
    { id: 'asian', name: 'Asian', categoryIds: ['19'] },
  ],
  usa: [
    { id: 'all', name: 'All', categoryIds: ['2'] },
    { id: '247', name: '24/7', categoryIds: ['24'] },
  ],
  pacific: [
    { id: 'all', name: 'All', categoryIds: ['54'] },  // 90 (Philippines) removed — 1/124 alive
    { id: 'australia', name: 'Australia', categoryIds: ['54'] },
  ],
  americas: [
    { id: 'all', name: 'All', categoryIds: ['31', '741'] },
  ],
  spinthewheel: [
    { id: 'all', name: 'All', categoryIds: ['275', '282', '57', '280', '274', '283'] },
    { id: 'english', name: 'English 24/7', categoryIds: ['275'] },
    { id: 'bollywood', name: 'Bollywood 24/7', categoryIds: ['282'] },
    { id: 'netflix', name: 'Netflix Loop', categoryIds: ['57'] },
  ],
};

// ── Premium 4K Sub-types ─────────────────────────────────────────

export const PREMIUM4K_TYPES: SportType[] = [
  { id: 'all', name: 'All 4K', categoryIds: ['578', '85', '87', '337', '340', '339', '356'] },
  { id: 'sports', name: 'Sports 4K', categoryIds: ['578', '85', '356'] },       // Sky Sports UHD, beIN 4K, India Sports 4K
  { id: 'movies', name: 'Movies 4K', categoryIds: ['87', '340', '339'] },       // beIN Movies 4K, India English/Hindi Movies 4K
  { id: 'docs', name: 'Docs 4K', categoryIds: ['337'] },                        // Discovery 4K, NatGeo 4K, Animal Planet 4K
];

// ── Browse Experiences ───────────────────────────────────────────
// Replaces raw Starshare categories with curated experience groups.
// Every live category mapped. Dead categories excluded.
// A category can appear in multiple experiences.

export interface BrowseExperience {
  id: string;
  name: string;
  icon: string;       // Lucide icon name hint for the UI
  categoryIds: string[];
}

export const BROWSE_EXPERIENCES: BrowseExperience[] = [
  // Broadest / strongest first — what most users tap
  {
    id: 'uk-usa',
    name: 'UK & USA',
    icon: 'tv',
    categoryIds: [
      '2',    // USA (93ch — HBO, Starz, Showtime)
      '3',    // UK Entertainment (39ch — Ch4, Comedy Central, Sky)
      '414',  // UK General (26ch — BBC One FHD, ITV FHD)
      '413',  // UK Movies (42ch)
      '24',   // US 24/7
      '411',  // HUB Premier (11ch)
    ],
  },
  {
    id: 'movies-247',
    name: 'Movies 24/7',
    icon: 'film',
    categoryIds: [
      '275',  // English Movies 24/7
      '57',   // Netflix Movies 24/7
      '280',  // Amazon Movies 24/7
      '413',  // UK Movies (42ch)
      '274',  // Bollywood Movies/Actors 24/7 (65ch)
      '282',  // Bollywood Movies 24/7
      '283',  // Hindi Web Series 24/7 (14ch)
      '349',  // 24x7 Live (34ch)
    ],
  },
  {
    id: 'sports-events',
    name: 'Live Events',
    icon: 'trophy',
    categoryIds: [
      '190',  // PPV Live Match Time (72ch)
      '807',  // IPL 2026 (9ch)
      '808',  // PSL 2026 (2ch)
    ],
  },
  // Cultural anchors — Africa & French together for SL/Guinea audience
  {
    id: 'africa',
    name: 'Africa',
    icon: 'globe',
    categoryIds: [
      '336',  // AFRICA CANAL+ (247ch)
      '343',  // DSTV Entertainment (84ch)
      '428',  // DSTV Entertainment FHD (72ch)
      '344',  // DSTV Movies (7ch)
      '429',  // DSTV Movies FHD (9ch)
      '347',  // DSTV Kids (13ch)
      '430',  // DSTV Kids FHD (15ch)
      '346',  // DSTV News (17ch)
      '431',  // DSTV News FHD (5ch)
      '345',  // DSTV Super — SuperSport
      '427',  // DSTV Super FHD
    ],
  },
  {
    id: 'french',
    name: 'French',
    icon: 'languages',
    categoryIds: [
      '11',   // France (162ch — Canal+, TF1, M6)
      '336',  // AFRICA CANAL+ (247ch — Africa Frenchn)
    ],
  },
  {
    id: 'arabic',
    name: 'Arabic & MENA',
    icon: 'moon',
    categoryIds: [
      '86',   // MBC Arabic (53ch)
      '180',  // Egypt (69ch)
      '751',  // Iran (97 alive)
      '129',  // Iraq (63 alive)
      '13',   // ARABIC (13ch)
      '549',  // Lebanon (24ch)
      '554',  // Morocco (19ch)
      '553',  // Algeria (25ch)
      '548',  // Syria (24ch)
      '556',  // UAE (25 alive)
      '83',   // Qatar (10ch)
      '227',  // Oman (1ch)
      '178',  // Kuwait (17ch)
      '181',  // Saudi Arabia (44ch)
      '175',  // Shahed Box (34ch)
      '165',  // Arabic News
      '156',  // Arabic Sports
      '555',  // Arabic Music
      '87',   // beIN Movies
      '123',  // Islamic
    ],
  },
  // Deep regional — massive catalogs
  {
    id: 'south-asian',
    name: 'South Asia',
    icon: 'landmark',
    categoryIds: [
      '247',  // India Entertainment
      '338',  // India Entertainment (additional)
      '340',  // India English Movies (29ch)
      '339',  // India Hindi Movies (23ch)
      '337',  // India Documentary (23ch)
      '356',  // India Sports
      '341',  // India Music (11ch)
      '77',   // Indian News (47ch)
      '18',   // Indian SD (49ch)
      '728',  // Malayalam Entertainment (33ch)
      '729',  // Malayalam Movies (65ch)
      '730',  // Malayalam News (29ch)
      '732',  // Tamil Entertainment (67ch)
      '733',  // Tamil Movies (37ch)
      '731',  // Tamil News (11ch)
      '72',   // Tamil (6ch)
      '73',   // Telugu (51ch)
      '290',  // Telugu Movies 24/7 (28ch)
      '81',   // Kannada (40ch)
      '291',  // Kannada Movies 24/7 (31ch)
      '76',   // Gujarati (20ch)
      '75',   // Marathi (32ch)
      '405',  // Oriya (16ch)
      '140',  // Assam (8ch)
      '560',  // Bhojpuri (4ch)
      '19',   // UK Asian (38ch)
      '194',  // USA Asian (35ch)
      '9',    // Bangla (88ch)
      '292',  // Bangla Movies 24/7 (8ch)
      '42',   // Sri Lanka (36ch)
      '64',   // Nepal (87ch)
      '28',   // Afghanistan (17 alive)
      '727',  // Malayalam News (15 alive)
    ],
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    icon: 'star',
    categoryIds: [
      '4',    // Pakistan (44ch)
      '98',   // Pakistan News (47ch)
      '350',  // Pak Drama 24/7 (13ch)
      '272',  // Pakistani Movies 24/7 (4ch)
      '7',    // Punjabi (83ch)
      '285',  // Punjabi Movies 24/7 (9ch)
      '287',  // Punjabi Singers 24/7
      '360',  // Pakistani Singers 24/7 (13 alive)
    ],
  },
  {
    id: 'europe',
    name: 'Europe',
    icon: 'map',
    categoryIds: [
      '15',   // Germany (277 alive)
      '25',   // Turkey (263 alive)
      '20',   // EXYU (240 alive)
      '71',   // Russian (196 alive)
      '44',   // Bulgaria (135 alive)
      '14',   // Italy (45ch)
      '16',   // Portugal (157ch)
      '39',   // Poland (192ch)
      '35',   // Romania (79ch)
      '29',   // Albania (107 alive)
      '21',   // Netherlands (68 alive)
      '774',  // Czech (57 alive)
      '63',   // Sweden (48 alive)
      '583',  // Norway (32 alive)
      '60',   // Austria (30 alive)
      '579',  // Denmark (27 alive)
      '582',  // Finland (32ch)
      '10',   // Greek (11 alive)
      '132',  // Israel (116ch)
      '141',  // New Zealand (5ch)
    ],
  },
  {
    id: 'americas',
    name: 'Americas',
    icon: 'globe',
    categoryIds: [
      '31',   // Canada (230 alive)
      '741',  // Canada Live Event (157 alive)
      '425',  // Caribbean (196 alive)
      '66',   // Brasil (75 alive)
    ],
  },
  {
    id: 'asia-pacific',
    name: 'Asia Pacific',
    icon: 'compass',
    categoryIds: [
      '90',   // Philippines (124ch)
      '101',  // Indonesia (91 alive)
      '48',   // Malaysia (200ch)
      '54',   // Australia (110 alive)
    ],
  },
  {
    id: 'sports-all',
    name: 'All Sports',
    icon: 'trophy',
    categoryIds: [
      '85',   // beIN Sports (132ch)
      '578',  // Real 4K (35ch)
      '353',  // Sky Sports UK 4K (10ch)
      '483',  // Sky Sports UK (32ch)
      '234',  // Football (31ch)
      '345',  // DStv Super (32ch)
      '427',  // DStv Super FHD (34ch)
      '492',  // EPL (31ch)
      '5',    // Cricket (59ch)
      '6',    // Sports General
      '342',  // Tennis/Racing
      '550',  // Rugby (20ch)
      '138',  // Boxing
      '212',  // Fighting
      '356',  // India Sports
      '156',  // Arabic Sports
      '137',  // Fox Australia Sports (8ch)
      '516',  // NFL
      '139',  // UK Sports Mix (10ch)
      '726',  // MLS (49ch)
      '328',  // MLB (32ch)
      '190',  // PPV Live Events (72ch)
      '807',  // IPL 2026 (9ch)
      '808',  // PSL 2026 (2ch)
      '542',  // Optus Sports (11 alive)
      '543',  // Spark Sports (8 alive)
      '773',  // NBA League Pass (5 alive)
    ],
  },
];

// Dead categories — EMPTY after two-tier verification (2026-03-30).
// Every category with even 1 verified channel has been removed from this list.
export const DEAD_CATEGORY_IDS = new Set([
  '213',  // Premium (2 channels, not useful)
]);

// ── Premium Gem Channels ─────────────────────────────────────────
/** Premium channels to always surface first within any category listing.
 *  Stream IDs sourced from the 2026-03-28 channel curation probe. */
// @deprecated — gems now tracked via is_gem in tivi_channels, built at runtime from curator
export const GEM_STREAM_IDS = new Set<number>();
