/**
 * DashTivi+ Collections — Curated content experiences
 *
 * Collections define WHAT to show and HOW to show it.
 * The homepage reads these to build a personalized, time-aware experience.
 *
 * Category IDs are from the Starshare/Xtream API.
 */

// ── Types ─────────────────────────────────────────────────────────

export interface Collection {
  id: string;
  name: string;
  emoji: string;
  description: string;
  type: 'live' | 'vod' | 'series';
  categoryIds: string[];
  /** Max items to show in a row */
  limit: number;
  /** Navigation target when tapping "See All" */
  navigateTo: string;
}

/** Smart collections are generated by the recommendation engine at runtime */
export interface SmartCollection {
  id: string;
  name: string;
  emoji: string;
  description: string;
  type: 'smart-vod' | 'smart-series';
  /** The underlying content type for rendering */
  contentType: 'vod' | 'series';
  navigateTo: string;
}

export interface CollectionCard {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  navigateTo: string;
}

export interface FeaturedHero {
  title: string;
  subtitle: string;
  cta: string;
  navigateTo: string;
  gradient: string;
}

// ── Homepage Row Collections ──────────────────────────────────────

export const HOMEPAGE_COLLECTIONS: Collection[] = [
  {
    id: 'live-sports',
    name: 'Live Sports',
    emoji: '\u26BD',
    description: 'Football, Cricket, Combat & more',
    type: 'live',
    categoryIds: [
      '234',  // Football
      '85',   // beIN Sports
      '345',  // DSTV Super Sports
      '5',    // Cricket
      '353',  // Sky Sports UK 4K
      '578',  // Real 4K
    ],
    limit: 15,
    navigateTo: '/live',
  },
  {
    id: 'fresh-movies',
    name: 'Fresh Movies',
    emoji: '\uD83C\uDFAC',
    description: 'Just added this year',
    type: 'vod',
    categoryIds: ['749', '597'], // English 2026, 2025
    limit: 15,
    navigateTo: '/movies',
  },
  {
    id: 'binge-worthy',
    name: 'Binge-Worthy',
    emoji: '\uD83C\uDF7F',
    description: 'Netflix, HBO, Disney+',
    type: 'series',
    categoryIds: ['106', '188', '102'], // Netflix, HBO Max, Disney+Hotstar
    limit: 15,
    navigateTo: '/series',
  },
  {
    id: 'african-tv',
    name: 'African Sports',
    emoji: '\u26BD',
    description: 'SuperSport, beIN Africa & more',
    type: 'live',
    categoryIds: ['345', '427', '156'], // DSTV Sports, DSTV Sports FHD, Arabic Sports (beIN Africa)
    limit: 15,
    navigateTo: '/live',
  },
  {
    id: 'news-world',
    name: 'News & World',
    emoji: '\uD83D\uDCF0',
    description: 'Stay informed, stay sharp',
    type: 'live',
    categoryIds: [
      '82',   // English News (CNN, BBC, Fox News, Al Jazeera)
      '417',  // UK News
      '165',  // Arabic News
    ],
    limit: 12,
    navigateTo: '/live',
  },
  {
    id: 'k-drama-turkish',
    name: 'K-Drama & Turkish Hits',
    emoji: '\uD83C\uDF1F',
    description: 'Korean & Turkish drama everyone\'s watching',
    type: 'series',
    categoryIds: ['267', '99'],  // Korean (235 series), Turkish (1,130 series)
    limit: 15,
    navigateTo: '/series',
  },
  {
    id: 'cinema-4k',
    name: '4K Cinema',
    emoji: '\uD83C\uDFA5',
    description: 'Crystal clear blockbusters',
    type: 'vod',
    categoryIds: ['122', '34'],  // 4K (1,058 movies), Blockbuster (1,002 movies)
    limit: 15,
    navigateTo: '/movies',
  },
  {
    id: 'fight-night',
    name: 'Fight Night',
    emoji: '\uD83E\uDD4A',
    description: 'UFC, WWE, PPV & Combat Sports',
    type: 'live',
    categoryIds: ['516'],  // NFL/Combat
    limit: 12,
    navigateTo: '/live',
  },
];

// ── Quick-tap Collection Cards (vibes navigation) ─────────────────

export const COLLECTION_CARDS: CollectionCard[] = [
  { id: 'sports', name: 'Sports', emoji: '\u26BD', gradient: 'from-green-600/40 to-emerald-900/40', navigateTo: '/live' },
  { id: 'news', name: 'News', emoji: '\uD83D\uDCF0', gradient: 'from-blue-600/40 to-blue-900/40', navigateTo: '/live' },
  { id: 'movies', name: 'Movies', emoji: '\uD83C\uDFAC', gradient: 'from-red-600/40 to-red-900/40', navigateTo: '/movies' },
  { id: 'series', name: 'Series', emoji: '\uD83D\uDCFA', gradient: 'from-purple-600/40 to-purple-900/40', navigateTo: '/series' },
  { id: 'africa', name: 'Africa', emoji: '\uD83C\uDF0D', gradient: 'from-amber-600/40 to-orange-900/40', navigateTo: '/french' },
  { id: 'kids', name: 'Kids', emoji: '\uD83E\uDDF8', gradient: 'from-pink-600/40 to-rose-900/40', navigateTo: '/live' },
  { id: 'music', name: 'Music', emoji: '\uD83C\uDFB5', gradient: 'from-fuchsia-600/40 to-pink-900/40', navigateTo: '/live' },
  { id: 'faith', name: 'Faith', emoji: '\uD83D\uDE4F', gradient: 'from-amber-500/40 to-yellow-900/40', navigateTo: '/live' },
];

// ── Time-aware Featured Hero ──────────────────────────────────────

export function getFeaturedHero(): FeaturedHero {
  const hour = new Date().getHours();

  // Morning (6am-12pm): News
  if (hour >= 6 && hour < 12) {
    return {
      title: 'Good Morning',
      subtitle: 'Catch up on what matters. Live news from around the world.',
      cta: 'Watch News',
      navigateTo: '/live',
      gradient: 'from-blue-600/20 via-[#0A0A0A] to-sky-900/10',
    };
  }

  // Afternoon (12pm-6pm): Movies
  if (hour >= 12 && hour < 18) {
    return {
      title: 'Afternoon Escape',
      subtitle: 'Thousands of movies waiting. Pick something fresh.',
      cta: 'Browse Movies',
      navigateTo: '/movies',
      gradient: 'from-amber-600/15 via-[#0A0A0A] to-orange-900/10',
    };
  }

  // Evening (6pm-11pm): Sports or Entertainment
  if (hour >= 18 && hour < 23) {
    return {
      title: 'Prime Time',
      subtitle: 'Live sports, new movies, and binge-worthy series. Your night starts here.',
      cta: 'Watch Live',
      navigateTo: '/live',
      gradient: 'from-primary/20 via-[#0A0A0A] to-primary-dark/10',
    };
  }

  // Late night (11pm-6am): Series / Chill
  return {
    title: 'Late Night',
    subtitle: 'Perfect time for a series. Start something new tonight.',
    cta: 'Find a Series',
    navigateTo: '/series',
    gradient: 'from-indigo-600/15 via-[#0A0A0A] to-violet-900/10',
  };
}

// ── Movie Featured Categories (reordered for audience) ────────────

export const MOVIE_FEATURED_CATS = [
  { id: '749', name: 'New 2026' },        // 214 movies
  { id: '597', name: '2025 Hits' },       // 2,120 movies
  { id: '525', name: '2024' },            // 2,614 movies
  { id: '122', name: '4K' },              // 1,058 movies
  { id: '34', name: 'Blockbuster' },      // 1,002 movies
  { id: '240', name: 'Award Winners' },   // 142 movies
  { id: '95', name: 'Turkish' },          // 853 movies (was 772 → only 28)
  { id: '33', name: 'Bollywood' },        // 2,683 movies (was 168 → only 51)
  { id: '69', name: 'Kids' },             // 440 movies
  { id: '96', name: 'Arabic Sub' },       // 684 movies (was 88 → only 3)
  { id: '148', name: 'Horror' },          // 188 movies
];

// ── Series Featured Categories ────────────────────────────────────

export const SERIES_FEATURED_CATS = [
  { id: '106', name: 'Netflix' },         // 2,532 series
  { id: '108', name: 'Prime Video' },     // 1,574 series
  { id: '102', name: 'Disney+' },         // 810 series (was 654 → only 49)
  { id: '188', name: 'HBO' },             // 380 series
  { id: '114', name: 'Apple TV+' },       // 346 series
  { id: '209', name: 'Hulu' },            // 334 series
  { id: '202', name: 'BBC' },             // 315 series
  { id: '249', name: 'Paramount+' },      // 154 series
  { id: '99', name: 'Turkish' },          // 1,130 series
  { id: '267', name: 'Korean' },          // 235 series
];

// ── Live TV Themed Collections ───────────────────────────────────

export interface LiveTheme {
  id: string;
  name: string;
  emoji: string;
  categoryIds: string[];
  gradient: string;
  glowColor: string;
}

export const LIVETV_THEMES: LiveTheme[] = [
  {
    id: 'sports',
    name: 'Sports',
    emoji: '\u26BD',
    categoryIds: [
      '234', '85', '345', '427', '353', '578', '5', '6', '342',
      '550', '138', '212', '356', '156', '137', '516', '483',
      '139', '492', '773', '726', '328',
    ],
    gradient: 'from-green-500 to-emerald-700',
    glowColor: 'shadow-green-500/20',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    emoji: '\u2728',
    categoryIds: [
      '3',    // UK Entertainment
      '2',    // USA
      '247',  // India Entertainment
      '19',   // UK Asian
      '414',  // UK General
      '338',  // India Entertainment
      '24',   // US 24/7
    ],
    gradient: 'from-purple-500 to-violet-700',
    glowColor: 'shadow-purple-500/20',
  },
  {
    id: 'news',
    name: 'News',
    emoji: '\uD83D\uDCF0',
    categoryIds: [
      '82',   // English News
      '417',  // UK News
      '165',  // Arabic News
      '730',  // Indian News
      '77',   // Indian News (additional)
      '98',   // Pakistan News
    ],
    gradient: 'from-blue-500 to-sky-700',
    glowColor: 'shadow-blue-500/20',
  },
  {
    id: 'kids',
    name: 'Kids & Family',
    emoji: '\uD83E\uDDF8',
    categoryIds: [
      '32',   // Kids (108ch — Nick, Disney, CN, CBeebies, PBS)
      '410',  // UK Kids
    ],
    gradient: 'from-pink-500 to-rose-600',
    glowColor: 'shadow-pink-500/20',
  },
  {
    id: 'movies247',
    name: 'Cinema 24/7',
    emoji: '\uD83C\uDFAC',
    categoryIds: [
      '275',  // English Movies 24/7
      '57',   // Netflix Movies 24/7
      '282',  // Bollywood Movies 24/7
      '87',   // beIN Movies (31ch)
      '280',  // Amazon Movies 24/7
      '339',  // India Hindi Movies
      '340',  // India English Movies
    ],
    gradient: 'from-red-500 to-rose-700',
    glowColor: 'shadow-red-500/20',
  },
  {
    id: 'music',
    name: 'Music & Vibes',
    emoji: '\uD83C\uDFB5',
    categoryIds: [
      '416',  // UK Music
      '341',  // India Music
      '555',  // Arabic Music
      '270',  // Bollywood Singers 24/7
      '287',  // Punjabi Singers 24/7
    ],
    gradient: 'from-fuchsia-500 to-pink-700',
    glowColor: 'shadow-fuchsia-500/20',
  },
  {
    id: 'documentary',
    name: 'Discovery',
    emoji: '\uD83C\uDF0E',
    categoryIds: [
      '337',  // India Documentary
      '415',  // UK Documentary
    ],
    gradient: 'from-teal-500 to-cyan-700',
    glowColor: 'shadow-teal-500/20',
  },
  {
    id: 'faith',
    name: 'Faith',
    emoji: '\uD83D\uDE4F',
    categoryIds: [
      '123',  // Islamic (156ch)
      '561',  // Christian (16ch)
    ],
    gradient: 'from-amber-500 to-yellow-700',
    glowColor: 'shadow-amber-500/20',
  },
];

// ── Sports Sub-types (for sub-tabs within Sports theme) ─────────

export interface SportType {
  id: string;
  name: string;
  categoryIds: string[];
}

// Child experiences within Sports — DASH-branded rooms
export const SPORT_TYPES: SportType[] = [
  { id: 'all', name: 'All Sports', categoryIds: ['234', '85', '345', '427', '353', '578', '5', '6', '342', '550', '138', '212', '356', '156', '137', '516', '483', '139', '492', '773', '726', '328'] },
  { id: 'football', name: 'Football Non-Stop', categoryIds: ['234', '492', '427'] },
  { id: 'bein', name: 'beIN Zone', categoryIds: ['85'] },
  { id: 'nba', name: 'Take a Hoop', categoryIds: ['773'] },
  { id: 'cricket', name: 'Cricket Ground', categoryIds: ['5'] },
  { id: 'nfl', name: 'NFL', categoryIds: ['516'] },
  { id: 'combat', name: 'The Ring', categoryIds: ['190'] },
  { id: 'fans', name: 'Fans Space', categoryIds: ['234'] },  // LFC TV, MUTV, team channels
  { id: 'africa', name: 'African Football', categoryIds: ['345', '427'] },
  { id: 'sky', name: 'Sky Sports', categoryIds: ['353', '483', '578'] },
  { id: 'racing', name: 'Speed', categoryIds: ['342'] },
  { id: 'rugby', name: 'Rugby', categoryIds: ['550'] },
  { id: 'more', name: 'More', categoryIds: ['138', '212', '726', '328', '6'] },
];

// ── Child Experiences — sub-tabs within each mother theme ─────────
// Same SportType interface reused for all child experiences

export const ENTERTAINMENT_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['3', '2', '247', '19', '414', '338', '24'] },
  { id: 'usa', name: 'USA Tonight', categoryIds: ['2'] },
  { id: 'uk', name: 'UK Lounge', categoryIds: ['3', '414'] },
  { id: 'african', name: 'African Drama', categoryIds: [] },  // Free channels (experience: entertainment, culture: africa)
  { id: 'reality', name: 'Reality Rush', categoryIds: [] },    // Free channels (experience: general)
  { id: 'asian', name: 'Asian Vibes', categoryIds: ['247', '338', '19'] },
];

export const KIDS_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['32', '410'] },
  { id: 'cartoons', name: 'Cartoon World', categoryIds: ['32'] },
  { id: 'littleones', name: 'Little Ones', categoryIds: ['32'] },   // Filtered by name: baby, rhyme, panda
  { id: 'adventure', name: 'Adventure', categoryIds: ['32'] },      // Filtered by name: avatar, paw patrol, spongebob
  { id: 'ukkids', name: 'UK Kids', categoryIds: ['410'] },
];

export const CINEMA_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['275', '57', '282', '87', '280', '339', '340'] },
  { id: 'action', name: 'Action Vault', categoryIds: ['275'] },     // Filtered: action/thriller channels
  { id: 'comedy', name: 'Comedy Corner', categoryIds: ['275'] },    // Filtered: comedy channels
  { id: 'horror', name: 'Horror Room', categoryIds: ['275'] },      // Filtered: horror channels
  { id: 'bollywood', name: 'Bollywood Palace', categoryIds: ['282', '339'] },
  { id: 'netflix', name: 'Netflix Loop', categoryIds: ['57'] },
  { id: 'bein', name: 'beIN Cinema', categoryIds: ['87'] },
];

export const MUSIC_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['416', '341', '555', '270', '287'] },
  { id: 'afro', name: 'Afro Beats', categoryIds: [] },              // Free channels (experience: music, culture: africa)
  { id: 'mtv', name: 'MTV World', categoryIds: ['416'] },
  { id: 'bollywood', name: 'Bollywood Beats', categoryIds: ['341', '270'] },
  { id: 'throwback', name: 'Throwback', categoryIds: ['416'] },     // Filtered: NOW 70s, 80s, 90s
  { id: 'arabic', name: 'Arabic Vibes', categoryIds: ['555'] },
];

export const DISCOVERY_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['337', '415'] },
  { id: 'wild', name: 'Wild Planet', categoryIds: ['337', '415'] },  // Filtered: animal, natgeo, bbc earth
  { id: 'science', name: 'Science Lab', categoryIds: ['337', '415'] }, // Filtered: discovery, science
  { id: 'history', name: 'History Vault', categoryIds: ['337', '415'] }, // Filtered: history, sky history
  { id: 'crime', name: 'Crime Files', categoryIds: ['415'] },        // Filtered: investigation, court
];

export const FAITH_TYPES: SportType[] = [
  { id: 'all', name: 'All', categoryIds: ['123', '561'] },
  { id: 'islamic', name: 'Islamic', categoryIds: ['123'] },
  { id: 'christian', name: 'Christian', categoryIds: ['561'] },
];

// ── WorldEX Region Genre Filters ─────────────────────────────────
// Genre pills within each WorldEX region — maps to Xtream category IDs
// "All" uses the region's default, genre pills load additional categories

export interface RegionGenre {
  id: string;
  name: string;
  categoryIds: string[];
}

export const REGION_GENRES: Record<string, RegionGenre[]> = {
  africa: [
    { id: 'all', name: 'All', categoryIds: ['345', '427'] },
    { id: 'sports', name: 'Sports', categoryIds: ['345', '427'] },
  ],
  france: [
    { id: 'all', name: 'All', categoryIds: ['11'] },
    { id: 'bein', name: 'beIN FR', categoryIds: ['156'] },
    { id: 'movies', name: 'beIN Movies', categoryIds: ['87'] },
  ],
  uk: [
    { id: 'all', name: 'All', categoryIds: ['3', '414'] },
    { id: 'sports', name: 'Sports', categoryIds: ['483', '353'] },
    { id: 'entertainment', name: 'Entertainment', categoryIds: ['3'] },
    { id: 'news', name: 'News', categoryIds: ['417'] },
    { id: 'movies', name: 'Movies', categoryIds: ['413'] },
    { id: 'kids', name: 'Kids', categoryIds: ['410'] },
    { id: 'documentary', name: 'Docs', categoryIds: ['415'] },
    { id: 'music', name: 'Music', categoryIds: ['416'] },
    { id: 'asian', name: 'Asian', categoryIds: ['19'] },
  ],
  usa: [
    { id: 'all', name: 'All', categoryIds: ['2'] },
    { id: '247', name: '24/7', categoryIds: ['24'] },
    { id: 'asian', name: 'Asian', categoryIds: ['194'] },
  ],
  arabic: [
    { id: 'all', name: 'All', categoryIds: ['86', '165', '156', '13'] },
    { id: 'mbc', name: 'MBC', categoryIds: ['86'] },
    { id: 'news', name: 'News', categoryIds: ['165'] },
    { id: 'sports', name: 'Sports', categoryIds: ['156'] },
    { id: 'music', name: 'Music', categoryIds: ['555'] },
    { id: 'shahed', name: 'Shahed', categoryIds: ['175'] },
    { id: 'movies', name: 'Movies', categoryIds: ['87'] },
    { id: 'egypt', name: 'Egypt', categoryIds: ['180'] },
    { id: 'iraq', name: 'Iraq', categoryIds: ['129'] },
    { id: 'lebanon', name: 'Lebanon', categoryIds: ['549'] },
    { id: 'syria', name: 'Syria', categoryIds: ['548'] },
    { id: 'morocco', name: 'Morocco', categoryIds: ['554'] },
    { id: 'algeria', name: 'Algeria', categoryIds: ['553'] },
    { id: 'saudi', name: 'Saudi', categoryIds: ['181'] },
    { id: 'uae', name: 'UAE', categoryIds: ['556'] },
    { id: 'qatar', name: 'Qatar', categoryIds: ['83'] },
    { id: 'kuwait', name: 'Kuwait', categoryIds: ['178'] },
    { id: 'oman', name: 'Oman', categoryIds: ['227'] },
  ],
  india: [
    { id: 'all', name: 'All', categoryIds: ['247', '338', '18'] },
    { id: 'entertainment', name: 'Entertainment', categoryIds: ['247', '338'] },
    { id: 'cricket', name: 'Cricket', categoryIds: ['5'] },
    { id: 'sports', name: 'Sports', categoryIds: ['356'] },
    { id: 'news', name: 'News', categoryIds: ['77', '730', '731'] },
    { id: 'documentary', name: 'Docs', categoryIds: ['337'] },
    { id: 'music', name: 'Music', categoryIds: ['341'] },
    { id: 'movies', name: 'Movies', categoryIds: ['339', '340'] },
    { id: 'bangla', name: 'Bangla', categoryIds: ['9'] },
    { id: 'tamil', name: 'Tamil', categoryIds: ['732', '733', '72'] },
    { id: 'telugu', name: 'Telugu', categoryIds: ['73', '290'] },
    { id: 'malayalam', name: 'Malayalam', categoryIds: ['728', '729', '727', '730'] },
    { id: 'kannada', name: 'Kannada', categoryIds: ['81', '291'] },
    { id: 'marathi', name: 'Marathi', categoryIds: ['75'] },
    { id: 'gujarati', name: 'Gujarati', categoryIds: ['76'] },
    { id: 'punjabi', name: 'Punjabi', categoryIds: ['7', '285'] },
  ],
  pakistan: [
    { id: 'all', name: 'All', categoryIds: ['4', '98'] },
    { id: 'news', name: 'News', categoryIds: ['98'] },
    { id: 'drama', name: 'Drama', categoryIds: ['350'] },
    { id: 'movies', name: 'Movies', categoryIds: ['272'] },
    { id: 'singers', name: 'Singers', categoryIds: ['360'] },
  ],
  turkey: [
    { id: 'all', name: 'All', categoryIds: ['25'] },
  ],
  germany: [
    { id: 'all', name: 'All', categoryIds: ['15'] },
  ],
  netherlands: [
    { id: 'all', name: 'All', categoryIds: ['21'] },
  ],
  brazil: [
    { id: 'all', name: 'All', categoryIds: ['66'] },
  ],
  iran: [
    { id: 'all', name: 'All', categoryIds: ['751'] },
  ],
  srilanka: [
    { id: 'all', name: 'All', categoryIds: ['42'] },
  ],
  nepal: [
    { id: 'all', name: 'All', categoryIds: ['64'] },
  ],
  philippines: [
    { id: 'all', name: 'All', categoryIds: ['90'] },
  ],
};
