// Auto-generated by enrich-tmdb.py — DO NOT EDIT MANUALLY
// Placeholder — run scripts/enrich-tmdb.py to populate

export interface TmdbEntry {
  i: number;      // tmdb_id
  g: number[];    // genre_ids
  r: number;      // vote_average
  v: number;      // vote_count
  y?: string;     // youtube trailer key
  o?: string;     // overview
  p?: string;     // poster_path
  t?: number;     // runtime (minutes)
}

export const TMDB_MAP: Record<string, TmdbEntry> = {};

export const TMDB_GENRES: Record<number, string> = {
  28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy',
  80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family',
  14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music',
  9648: 'Mystery', 10749: 'Romance', 878: 'Sci-Fi', 10770: 'TV Movie',
  53: 'Thriller', 10752: 'War', 37: 'Western',
};
